--- #YAML:1.0
name:                DBIx-Class-Tree-NestedSet
version:             0.07
abstract:            Manage trees of data using the nested set model
license:             ~
author:              
    - Ian Docherty <cpan@icydee.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBICx::TestDatabase:           0.01
    DBIx::Class:                   0.08
    Moose:                         0.54
    namespace::autoclean:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
